#Broker

broker:
  topicTemplate: "/1/{0,number,#}/raw"
  qos: 2
  url: "tcp://127.0.0.1:1883"
  clientId: JavaSample
scheduler:
  interval: 1000
message:
  deviceId: ${random.int[123400,123405]}
  rpm: ${random.int[0,8000]}
  directionTemp: ${random.int[0,8]}
  speed: ${random.int[0,120]}
  distance: ${random.int[0,1600]}
device:
  id: ${random.int[123400,123405]}
  typeTemp: ${random.int[0,2]}
